/**
 * Personalized card moves — fixed bank + decision tree (pokegit-moves-spec.md).
 *
 * Moves are selected from MOVE_BANK via thresholds on flat SignalValues, not
 * generated by an LLM. Only move ids are cached on the profile; name, type,
 * power, and description are always resolved live from the bank on read.
 *
 * Each signal family (all tiers of a given `signal`) shares one consistent
 * `type`, the same way a real move family (Ember -> Flamethrower -> Fire
 * Blast) stays a single type across power tiers.
 */

import type {
  DerivedSignals,
  PokemonType,
  RawGitHubData,
  SelectedMove,
} from "@/lib/types";

/** Card display shape for a selected move (pips, damage, flavor). */
export interface CardMove {
  name: string;
  /** Energy cost, one pip per entry. */
  cost: PokemonType[];
  damage: string;
  text: string;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SignalCategory =
  | "commit_timing"
  | "streak_consistency"
  | "collaboration"
  | "language_stack"
  | "repo_scale"
  | "commit_style";

export interface Move {
  id: string;
  name: string;
  type: PokemonType;
  power: number;
  category: SignalCategory;
  signal: string;
  /** 1 = mildest, higher = more extreme within the same signal. */
  tier: number;
  threshold: {
    metric: keyof SignalValues;
    /** Inclusive lower bound. */
    min?: number;
    /** Exclusive upper bound — keeps tiers within a signal non-overlapping. */
    max?: number;
  };
  description: string;
}

/**
 * Flat metrics the move bank thresholds against. Computed from DerivedSignals
 * + raw GitHub aggregates — no extra API calls.
 *
 * Fraction fields are 0–1. Counts/days/lengths are raw units.
 */
export interface SignalValues {
  pctCommitsAfterMidnight: number;
  pctCommitsEarlyMorning: number;
  pctCommitsEvening: number;
  pctCommitsWeekend: number;
  longestStreakDays: number;
  currentStreakDays: number;
  longestGapDays: number;
  dailyVariance: number;
  activeDays: number;
  totalReviews: number;
  totalPRs: number;
  reviewsPerCommit: number;
  collabRatio: number;
  languageCount: number;
  primaryLanguagePct: number;
  languageConcentration: number;
  repoCount: number;
  starCount: number;
  starConcentration: number;
  starsPerRepo: number;
  followerCount: number;
  avgCommitMessageLength: number;
  maxDailyContributions: number;
  meanDailyContributions: number;
  totalCommits: number;
}

// ---------------------------------------------------------------------------
// Signal computation
// ---------------------------------------------------------------------------

export function computeSignalValues(
  raw: RawGitHubData,
  signals: DerivedSignals,
): SignalValues {
  const commits = raw.contributions.totalCommitContributions;
  return {
    pctCommitsAfterMidnight: signals.timeOfDay.lateNight,
    pctCommitsEarlyMorning: signals.timeOfDay.earlyMorning,
    pctCommitsEvening: signals.timeOfDay.evening,
    pctCommitsWeekend: signals.weekendShare,
    longestStreakDays: signals.streaks.longest,
    currentStreakDays: signals.streaks.current,
    longestGapDays: signals.streaks.longestGap,
    dailyVariance: signals.dailyVariance,
    activeDays: signals.streaks.activeDays,
    totalReviews: signals.reviewsGiven,
    totalPRs: raw.pullRequestsOpened,
    reviewsPerCommit: signals.reviewsPerCommit,
    collabRatio: signals.reviewsPerCommit + signals.issuesPerCommit,
    languageCount: signals.meaningfulLanguageCount,
    primaryLanguagePct: signals.topLanguageShare,
    languageConcentration: signals.languageConcentration,
    repoCount: signals.nonForkRepoCount,
    starCount: signals.totalStars,
    starConcentration: signals.starConcentration,
    starsPerRepo: signals.starsPerRepo,
    followerCount: raw.profile.followers,
    avgCommitMessageLength: signals.avgCommitMessageLength,
    maxDailyContributions: signals.maxDailyContributions,
    meanDailyContributions: signals.meanDailyContributions,
    totalCommits: commits,
  };
}

// ---------------------------------------------------------------------------
// Move bank (~50 tiered entries + per-category defaults)
//
// Type key per signal family:
//   commit_hour_late_night  -> Dark
//   commit_hour_early       -> Fire
//   weekend_activity        -> Fighting
//   longest_streak          -> Steel
//   current_streak          -> Electric
//   longest_gap             -> Ice
//   daily_variance          -> Dark
//   review_volume           -> Psychic
//   pr_volume               -> Water
//   reviews_per_commit      -> Fairy
//   collab_ratio            -> Psychic
//   language_count          -> Psychic
//   primary_language_pct    -> Steel
//   language_concentration  -> Grass
//   repo_count              -> Ground
//   star_count              -> Fire
//   star_concentration      -> Electric
//   follower_count          -> Flying
//   commit_message_length   -> Psychic
//   max_daily               -> Electric
//   total_commits           -> Steel
// ---------------------------------------------------------------------------

export const MOVE_BANK: Move[] = [
  // === commit_timing ========================================================
  // signal: commit_hour_late_night (Dark)
  {
    id: "night_commit",
    name: "Night Commit",
    type: "Dark",
    power: 45,
    category: "commit_timing",
    signal: "commit_hour_late_night",
    tier: 1,
    threshold: { metric: "pctCommitsAfterMidnight", min: 0.15, max: 0.3 },
    description:
      "Commits slip out under cover of darkness after midnight, while the rest of the timezone sleeps.",
  },
  {
    id: "midnight_push",
    name: "Midnight Push",
    type: "Dark",
    power: 70,
    category: "commit_timing",
    signal: "commit_hour_late_night",
    tier: 2,
    threshold: { metric: "pctCommitsAfterMidnight", min: 0.3, max: 0.5 },
    description:
      "Work thrives in the dark hours — a large share of pushes land after the clock turns over.",
  },
  {
    id: "three_am_refactor",
    name: "3AM Refactor",
    type: "Dark",
    power: 95,
    category: "commit_timing",
    signal: "commit_hour_late_night",
    tier: 3,
    threshold: { metric: "pctCommitsAfterMidnight", min: 0.5 },
    description:
      "Half the activity happens deep in the dark, well after everyone else has logged off for the night.",
  },

  // signal: commit_hour_early (Fire)
  {
    id: "dawn_patch",
    name: "Dawn Patch",
    type: "Fire",
    power: 40,
    category: "commit_timing",
    signal: "commit_hour_early",
    tier: 1,
    threshold: { metric: "pctCommitsEarlyMorning", min: 0.15, max: 0.3 },
    description:
      "Fixes catch the first light before sunrise, landing warm and ready ahead of the morning stand-up.",
  },
  {
    id: "early_bird_push",
    name: "Early Bird Push",
    type: "Fire",
    power: 65,
    category: "commit_timing",
    signal: "commit_hour_early",
    tier: 2,
    threshold: { metric: "pctCommitsEarlyMorning", min: 0.3, max: 0.5 },
    description:
      "A spark catches early — momentum ignites and peaks in the first hours after waking.",
  },
  {
    id: "sunrise_ship",
    name: "Sunrise Ship",
    type: "Fire",
    power: 90,
    category: "commit_timing",
    signal: "commit_hour_early",
    tier: 3,
    threshold: { metric: "pctCommitsEarlyMorning", min: 0.5 },
    description:
      "Commits burn bright before the sun comes up, beating sunrise more often than not.",
  },

  // signal: weekend_activity (Fighting)
  {
    id: "saturday_deploy",
    name: "Saturday Deploy",
    type: "Fighting",
    power: 50,
    category: "commit_timing",
    signal: "weekend_activity",
    tier: 1,
    threshold: { metric: "pctCommitsWeekend", min: 0.25, max: 0.4 },
    description:
      "An ordinary day off still throws a few practice swings — a small but real push against downtime.",
  },
  {
    id: "weekend_warrior",
    name: "Weekend Warrior",
    type: "Fighting",
    power: 75,
    category: "commit_timing",
    signal: "weekend_activity",
    tier: 2,
    threshold: { metric: "pctCommitsWeekend", min: 0.4, max: 0.55 },
    description:
      "Saturday and Sunday turn into a real battleground, carrying serious fighting weight in the year's output.",
  },
  {
    id: "no_weekdays",
    name: "No Weekdays",
    type: "Fighting",
    power: 100,
    category: "commit_timing",
    signal: "weekend_activity",
    tier: 3,
    threshold: { metric: "pctCommitsWeekend", min: 0.55 },
    description:
      "The real fight happens on weekends — weekdays barely show up to throw a punch.",
  },

  // === streak_consistency ===================================================
  // signal: longest_streak (Steel)
  {
    id: "hot_streak",
    name: "Hot Streak",
    type: "Steel",
    power: 45,
    category: "streak_consistency",
    signal: "longest_streak",
    tier: 1,
    threshold: { metric: "longestStreakDays", min: 7, max: 30 },
    description:
      "A streak runs white-hot for over a week straight, already starting to harden into something built to last.",
  },
  {
    id: "iron_will",
    name: "Iron Will",
    type: "Steel",
    power: 70,
    category: "streak_consistency",
    signal: "longest_streak",
    tier: 2,
    threshold: { metric: "longestStreakDays", min: 30, max: 100 },
    description:
      "An unyielding, ironclad month-long run of activity — missed days are rare enough to notice.",
  },
  {
    id: "unbroken_chain",
    name: "Unbroken Chain",
    type: "Steel",
    power: 110,
    category: "streak_consistency",
    signal: "longest_streak",
    tier: 3,
    threshold: { metric: "longestStreakDays", min: 100 },
    description:
      "Forged over a hundred consecutive days, this streak holds without a single link breaking.",
  },

  // signal: current_streak (Electric)
  {
    id: "still_going",
    name: "Still Going",
    type: "Electric",
    power: 40,
    category: "streak_consistency",
    signal: "current_streak",
    tier: 1,
    threshold: { metric: "currentStreakDays", min: 3, max: 14 },
    description:
      "A small charge is starting to build — the streak hasn't broken yet.",
  },
  {
    id: "on_a_roll",
    name: "On a Roll",
    type: "Electric",
    power: 65,
    category: "streak_consistency",
    signal: "current_streak",
    tier: 2,
    threshold: { metric: "currentStreakDays", min: 14, max: 40 },
    description:
      "Momentum is charging up — two weeks or more of activity keeps sparking forward.",
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    type: "Electric",
    power: 95,
    category: "streak_consistency",
    signal: "current_streak",
    tier: 3,
    threshold: { metric: "currentStreakDays", min: 40 },
    description:
      "The current streak surges like unchecked voltage, deep into marathon territory with no sign of slowing.",
  },

  // signal: longest_gap (Ice)
  {
    id: "short_break",
    name: "Short Break",
    type: "Ice",
    power: 40,
    category: "streak_consistency",
    signal: "longest_gap",
    tier: 1,
    threshold: { metric: "longestGapDays", min: 14, max: 45 },
    description:
      "Activity briefly freezes over for a few weeks at a time, then thaws right back into motion.",
  },
  {
    id: "hibernation",
    name: "Hibernation",
    type: "Ice",
    power: 65,
    category: "streak_consistency",
    signal: "longest_gap",
    tier: 2,
    threshold: { metric: "longestGapDays", min: 45, max: 90 },
    description:
      "Long, ice-cold stretches of dormancy break up the year, like the profile is hibernating through winter.",
  },
  {
    id: "ghost_protocol",
    name: "Ghost Protocol",
    type: "Ice",
    power: 90,
    category: "streak_consistency",
    signal: "longest_gap",
    tier: 3,
    threshold: { metric: "longestGapDays", min: 90 },
    description:
      "Entire months freeze over without a trace, then eventually thaw back into activity.",
  },

  // signal: daily_variance (Dark)
  {
    id: "uneven_pace",
    name: "Uneven Pace",
    type: "Dark",
    power: 50,
    category: "streak_consistency",
    signal: "daily_variance",
    tier: 1,
    threshold: { metric: "dailyVariance", min: 1.5, max: 2.2 },
    description:
      "Daily output shifts unpredictably, shadowy and hard to read from one day to the next.",
  },
  {
    id: "burst_fire",
    name: "Burst Fire",
    type: "Dark",
    power: 75,
    category: "streak_consistency",
    signal: "daily_variance",
    tier: 2,
    threshold: { metric: "dailyVariance", min: 2.2, max: 3.5 },
    description:
      "Work flares up in sudden, shadowy bursts before quietly going dark again.",
  },
  {
    id: "chaos_mode",
    name: "Chaos Mode",
    type: "Dark",
    power: 100,
    category: "streak_consistency",
    signal: "daily_variance",
    tier: 3,
    threshold: { metric: "dailyVariance", min: 3.5 },
    description:
      "Contribution volume swings wildly and unpredictably, like it's operating in the dark with no set pattern.",
  },

  // === collaboration ========================================================
  // signal: review_volume (Psychic)
  {
    id: "code_glance",
    name: "Code Glance",
    type: "Psychic",
    power: 45,
    category: "collaboration",
    signal: "review_volume",
    tier: 1,
    threshold: { metric: "totalReviews", min: 10, max: 50 },
    description:
      "A psychic-level read on other people's code — reviews happen at a noticeable, attentive clip.",
  },
  {
    id: "review_barrage",
    name: "Review Barrage",
    type: "Psychic",
    power: 70,
    category: "collaboration",
    signal: "review_volume",
    tier: 2,
    threshold: { metric: "totalReviews", min: 50, max: 150 },
    description:
      "A steady mental barrage of review comments rains down on other people's pull requests.",
  },
  {
    id: "gatekeeper",
    name: "Gatekeeper",
    type: "Psychic",
    power: 105,
    category: "collaboration",
    signal: "review_volume",
    tier: 3,
    threshold: { metric: "totalReviews", min: 150 },
    description:
      "Review volume dominates like a mental checkpoint — most effort goes into deciding what gets through, not writing it.",
  },

  // signal: pr_volume (Water)
  {
    id: "pull_request",
    name: "Pull Request",
    type: "Water",
    power: 45,
    category: "collaboration",
    signal: "pr_volume",
    tier: 1,
    threshold: { metric: "totalPRs", min: 5, max: 30 },
    description:
      "Pull requests flow in at a steady trickle — change routes through review as standard practice.",
  },
  {
    id: "merge_storm",
    name: "Merge Storm",
    type: "Water",
    power: 70,
    category: "collaboration",
    signal: "pr_volume",
    tier: 2,
    threshold: { metric: "totalPRs", min: 30, max: 100 },
    description:
      "Pull requests pile up like rising water — integration becomes the main current of the work.",
  },
  {
    id: "pr_avalanche",
    name: "PR Avalanche",
    type: "Water",
    power: 100,
    category: "collaboration",
    signal: "pr_volume",
    tier: 3,
    threshold: { metric: "totalPRs", min: 100 },
    description:
      "A flood of pull requests thunders through — the queue itself becomes a rushing current all its own.",
  },

  // signal: reviews_per_commit (Fairy)
  {
    id: "peer_check",
    name: "Peer Check",
    type: "Fairy",
    power: 50,
    category: "collaboration",
    signal: "reviews_per_commit",
    tier: 1,
    threshold: { metric: "reviewsPerCommit", min: 0.05, max: 0.2 },
    description:
      "A light, fairy-dust sprinkle of reviews shows up alongside commits — collaboration isn't an afterthought.",
  },
  {
    id: "review_first",
    name: "Review First",
    type: "Fairy",
    power: 75,
    category: "collaboration",
    signal: "reviews_per_commit",
    tier: 2,
    threshold: { metric: "reviewsPerCommit", min: 0.2, max: 0.5 },
    description:
      "Reviewing others takes on a near-magical priority, rivaling the effort spent shipping original code.",
  },
  {
    id: "review_overlord",
    name: "Review Overlord",
    type: "Fairy",
    power: 110,
    category: "collaboration",
    signal: "reviews_per_commit",
    tier: 3,
    threshold: { metric: "reviewsPerCommit", min: 0.5 },
    description:
      "Reviews outpace commits by a wide margin, as if some enchanted oversight watches over every merge.",
  },

  // signal: collab_ratio (Psychic)
  {
    id: "pair_programming",
    name: "Pair Programming",
    type: "Psychic",
    power: 55,
    category: "collaboration",
    signal: "collab_ratio",
    tier: 1,
    threshold: { metric: "collabRatio", min: 0.15, max: 0.35 },
    description:
      "A synced, almost telepathic rhythm — reviews and issues show up as a steady mental presence next to every batch of commits.",
  },
  {
    id: "team_sync",
    name: "Team Sync",
    type: "Psychic",
    power: 80,
    category: "collaboration",
    signal: "collab_ratio",
    tier: 2,
    threshold: { metric: "collabRatio", min: 0.35, max: 0.7 },
    description:
      "Discussion and review form a shared headspace, like the whole team thinks through every decision together.",
  },
  {
    id: "collective_mind",
    name: "Collective Mind",
    type: "Psychic",
    power: 105,
    category: "collaboration",
    signal: "collab_ratio",
    tier: 3,
    threshold: { metric: "collabRatio", min: 0.7 },
    description:
      "Own commits are outnumbered by a collective, hive-mind level of collaborative signal.",
  },

  // === language_stack =======================================================
  // signal: language_count (Psychic)
  {
    id: "bilingual",
    name: "Bilingual",
    type: "Psychic",
    power: 45,
    category: "language_stack",
    signal: "language_count",
    tier: 1,
    threshold: { metric: "languageCount", min: 2, max: 4 },
    description:
      "At least two languages share real space in the same mind behind the code.",
  },
  {
    id: "polyglot",
    name: "Polyglot",
    type: "Psychic",
    power: 75,
    category: "language_stack",
    signal: "language_count",
    tier: 2,
    threshold: { metric: "languageCount", min: 4, max: 6 },
    description:
      "Four or more languages coexist, as if the mind behind the code thinks in many tongues at once.",
  },
  {
    id: "tower_of_babel",
    name: "Tower of Babel",
    type: "Psychic",
    power: 100,
    category: "language_stack",
    signal: "language_count",
    tier: 3,
    threshold: { metric: "languageCount", min: 6 },
    description:
      "A sprawling mix of languages coexists, as if one mind is holding too many tongues at once.",
  },

  // signal: primary_language_pct (Steel)
  {
    id: "focused_stack",
    name: "Focused Stack",
    type: "Steel",
    power: 50,
    category: "language_stack",
    signal: "primary_language_pct",
    tier: 1,
    threshold: { metric: "primaryLanguagePct", min: 0.6, max: 0.8 },
    description:
      "One language forms the core structure — solid steel beneath most of the work.",
  },
  {
    id: "specialist",
    name: "Specialist",
    type: "Steel",
    power: 75,
    category: "language_stack",
    signal: "primary_language_pct",
    tier: 2,
    threshold: { metric: "primaryLanguagePct", min: 0.8, max: 0.95 },
    description:
      "Nearly everything is forged in a single, steel-strong preferred language.",
  },
  {
    id: "monoculture",
    name: "Monoculture",
    type: "Steel",
    power: 95,
    category: "language_stack",
    signal: "primary_language_pct",
    tier: 3,
    threshold: { metric: "primaryLanguagePct", min: 0.95 },
    description:
      "One language is effectively the entire steel structure of the profile.",
  },

  // signal: language_concentration (Grass) — lower value = more even, non-overlapping bands
  {
    id: "even_spread",
    name: "Even Spread",
    type: "Grass",
    power: 55,
    category: "language_stack",
    signal: "language_concentration",
    tier: 1,
    threshold: { metric: "languageConcentration", min: 0.2, max: 0.4 },
    description:
      "Effort takes root across several languages evenly, without one variety overgrowing the rest.",
  },
  {
    id: "balanced_toolkit",
    name: "Balanced Toolkit",
    type: "Grass",
    power: 70,
    category: "language_stack",
    signal: "language_concentration",
    tier: 2,
    threshold: { metric: "languageConcentration", min: 0, max: 0.2 },
    description:
      "Languages grow side by side in unusually even proportions, like a well-tended garden.",
  },

  // === repo_scale ===========================================================
  // signal: repo_count (Ground)
  {
    id: "side_projects",
    name: "Side Projects",
    type: "Ground",
    power: 40,
    category: "repo_scale",
    signal: "repo_count",
    tier: 1,
    threshold: { metric: "repoCount", min: 5, max: 20 },
    description:
      "A modest patch of owned repositories takes root — ideas get their own plot of ground.",
  },
  {
    id: "repo_farm",
    name: "Repo Farm",
    type: "Ground",
    power: 70,
    category: "repo_scale",
    signal: "repo_count",
    tier: 2,
    threshold: { metric: "repoCount", min: 20, max: 50 },
    description:
      "Dozens of repositories are cultivated across the ground, systems built plot by plot.",
  },
  {
    id: "empire",
    name: "Empire",
    type: "Ground",
    power: 105,
    category: "repo_scale",
    signal: "repo_count",
    tier: 3,
    threshold: { metric: "repoCount", min: 50 },
    description:
      "A sprawling territory of owned repos spreads across the map — scale itself is the domain.",
  },

  // signal: star_count (Fire)
  {
    id: "rising_stars",
    name: "Rising Stars",
    type: "Fire",
    power: 50,
    category: "repo_scale",
    signal: "star_count",
    tier: 1,
    threshold: { metric: "starCount", min: 10, max: 100 },
    description:
      "A first spark of attention flickers across the public work.",
  },
  {
    id: "star_magnet",
    name: "Star Magnet",
    type: "Fire",
    power: 80,
    category: "repo_scale",
    signal: "star_count",
    tier: 2,
    threshold: { metric: "starCount", min: 100, max: 1000 },
    description:
      "Attention builds like gathering embers — hundreds of stars drawn in by the heat of the work.",
  },
  {
    id: "supernova",
    name: "Supernova",
    type: "Fire",
    power: 120,
    category: "repo_scale",
    signal: "star_count",
    tier: 3,
    threshold: { metric: "starCount", min: 1000 },
    description:
      "Star counts explode past a thousand, burning as bright and sudden as a supernova.",
  },

  // signal: star_concentration (Electric)
  {
    id: "breakout_hit",
    name: "Breakout Hit",
    type: "Electric",
    power: 60,
    category: "repo_scale",
    signal: "star_concentration",
    tier: 1,
    threshold: { metric: "starConcentration", min: 0.5, max: 0.75 },
    description:
      "One repository sparks and carries most of the attention, like a jolt of electricity through the whole profile.",
  },
  {
    id: "one_hit_wonder",
    name: "One-Hit Wonder",
    type: "Electric",
    power: 85,
    category: "repo_scale",
    signal: "star_concentration",
    tier: 2,
    threshold: { metric: "starConcentration", min: 0.75, max: 0.9 },
    description:
      "Nearly every star arcs toward a single breakout repo, the rest barely registering a charge.",
  },
  {
    id: "singular_fame",
    name: "Singular Fame",
    type: "Electric",
    power: 110,
    category: "repo_scale",
    signal: "star_concentration",
    tier: 3,
    threshold: { metric: "starConcentration", min: 0.9 },
    description:
      "One project carries the entire charge — everything else barely registers a spark by comparison.",
  },

  // signal: follower_count (Flying)
  {
    id: "watched",
    name: "Watched",
    type: "Flying",
    power: 45,
    category: "repo_scale",
    signal: "follower_count",
    tier: 1,
    threshold: { metric: "followerCount", min: 50, max: 300 },
    description:
      "A noticeable following starts to circle overhead, keeping an eye on the profile.",
  },
  {
    id: "followed",
    name: "Followed",
    type: "Flying",
    power: 75,
    category: "repo_scale",
    signal: "follower_count",
    tier: 2,
    threshold: { metric: "followerCount", min: 300, max: 2000 },
    description:
      "Hundreds of followers extend the profile's reach, letting its reputation fly well past the code itself.",
  },
  {
    id: "celebrity",
    name: "Celebrity",
    type: "Flying",
    power: 115,
    category: "repo_scale",
    signal: "follower_count",
    tier: 3,
    threshold: { metric: "followerCount", min: 2000 },
    description:
      "A very large following carries the name far past the code itself, out over a much wider reach.",
  },

  // === commit_style =========================================================
  // signal: commit_message_length (Psychic)
  {
    id: "one_liner",
    name: "One-Liner",
    type: "Psychic",
    power: 40,
    category: "commit_style",
    signal: "commit_message_length",
    tier: 1,
    threshold: { metric: "avgCommitMessageLength", min: 1, max: 30 },
    description:
      "Commit subjects stay short and to the point — just enough signal, no extra noise.",
  },
  {
    id: "proper_subject",
    name: "Proper Subject",
    type: "Psychic",
    power: 60,
    category: "commit_style",
    signal: "commit_message_length",
    tier: 2,
    threshold: { metric: "avgCommitMessageLength", min: 30, max: 72 },
    description:
      "Commit titles hit a healthy middle ground — clear enough to read the intent at a glance, short enough not to overthink it.",
  },
  {
    id: "wall_of_text",
    name: "Wall of Text",
    type: "Psychic",
    power: 90,
    category: "commit_style",
    signal: "commit_message_length",
    tier: 3,
    threshold: { metric: "avgCommitMessageLength", min: 72 },
    description:
      "Commit messages run long, like a stream-of-consciousness psychic download that does half the explaining for you.",
  },

  // signal: max_daily (Electric)
  {
    id: "busy_day",
    name: "Busy Day",
    type: "Electric",
    power: 50,
    category: "commit_style",
    signal: "max_daily",
    tier: 1,
    threshold: { metric: "maxDailyContributions", min: 15, max: 40 },
    description:
      "At least one day sparks well above the usual pace, like a jolt of electricity through the routine.",
  },
  {
    id: "power_day",
    name: "Power Day",
    type: "Electric",
    power: 80,
    category: "commit_style",
    signal: "max_daily",
    tier: 2,
    threshold: { metric: "maxDailyContributions", min: 40, max: 80 },
    description:
      "A single day pushes contribution output into a real power surge, far above the rest of the year.",
  },
  {
    id: "overclock",
    name: "Overclock",
    type: "Electric",
    power: 115,
    category: "commit_style",
    signal: "max_daily",
    tier: 3,
    threshold: { metric: "maxDailyContributions", min: 80 },
    description:
      "Peak daily output pushes voltage past its normal limit — the ceiling runs electric and high.",
  },

  // signal: total_commits (Steel)
  {
    id: "steady_hands",
    name: "Steady Hands",
    type: "Steel",
    power: 45,
    category: "commit_style",
    signal: "total_commits",
    tier: 1,
    threshold: { metric: "totalCommits", min: 100, max: 500 },
    description:
      "A solid, steady year of commits — volume without spectacle.",
  },
  {
    id: "commit_machine",
    name: "Commit Machine",
    type: "Steel",
    power: 80,
    category: "commit_style",
    signal: "total_commits",
    tier: 2,
    threshold: { metric: "totalCommits", min: 500, max: 2000 },
    description:
      "Commits run like clockwork through a steel-built machine — hundreds to thousands, powered by pure throughput.",
  },
  {
    id: "infinite_loop",
    name: "Infinite Loop",
    type: "Steel",
    power: 110,
    category: "commit_style",
    signal: "total_commits",
    tier: 3,
    threshold: { metric: "totalCommits", min: 2000 },
    description:
      "Commit count spirals into overdrive — a machine that never seems to power down.",
  },
];

/**
 * Soft fallbacks for sparse profiles — one per category, used only when the
 * decision tree cannot fill both move slots from real threshold matches.
 */
export const DEFAULT_MOVES: Record<SignalCategory, Move> = {
  commit_timing: {
    id: "default_day_shift",
    name: "Day Shift",
    type: "Normal",
    power: 35,
    category: "commit_timing",
    signal: "default",
    tier: 0,
    threshold: { metric: "pctCommitsAfterMidnight" },
    description: "No strong timing pattern. Work lands across ordinary hours.",
  },
  streak_consistency: {
    id: "default_casual_pace",
    name: "Casual Pace",
    type: "Normal",
    power: 35,
    category: "streak_consistency",
    signal: "default",
    tier: 0,
    threshold: { metric: "longestStreakDays" },
    description: "No dominant streak signal. Activity comes and goes.",
  },
  collaboration: {
    id: "default_solo_push",
    name: "Solo Push",
    type: "Normal",
    power: 35,
    category: "collaboration",
    signal: "default",
    tier: 0,
    threshold: { metric: "totalReviews" },
    description: "Little collaborative signal yet. Most work is self-directed.",
  },
  language_stack: {
    id: "default_hello_world",
    name: "Hello World",
    type: "Normal",
    power: 30,
    category: "language_stack",
    signal: "default",
    tier: 0,
    threshold: { metric: "languageCount" },
    description: "Language mix is thin or unclear. The stack is still forming.",
  },
  repo_scale: {
    id: "default_fresh_clone",
    name: "Fresh Clone",
    type: "Normal",
    power: 30,
    category: "repo_scale",
    signal: "default",
    tier: 0,
    threshold: { metric: "repoCount" },
    description: "Scale signals are quiet. Reach and repo count are still low.",
  },
  commit_style: {
    id: "default_wip",
    name: "WIP",
    type: "Normal",
    power: 30,
    category: "commit_style",
    signal: "default",
    tier: 0,
    threshold: { metric: "totalCommits" },
    description: "Not enough commit-style signal to specialize further.",
  },
};

const CATEGORY_ORDER: SignalCategory[] = [
  "commit_timing",
  "streak_consistency",
  "collaboration",
  "language_stack",
  "repo_scale",
  "commit_style",
];

// ---------------------------------------------------------------------------
// Decision tree
// ---------------------------------------------------------------------------

interface RankedMove {
  move: Move;
  value: number;
  strength: number;
}

function inThreshold(
  value: number,
  threshold: Move["threshold"],
): boolean {
  if (!Number.isFinite(value)) return false;
  if (threshold.min != null && value < threshold.min) return false;
  if (threshold.max != null && value >= threshold.max) return false;
  // A threshold with neither min nor max would match everything — reject.
  if (threshold.min == null && threshold.max == null) return false;
  return true;
}

/**
 * How far the value sits past the tier's entry threshold, normalized to ~0–1+.
 * Higher = more distinctive / extreme within that tier band.
 *
 * For ascending signals (higher = more extreme) strength grows from `min`.
 * For low-is-extreme bands (tier rises as the value falls, e.g. language
 * concentration) strength grows toward the lower end of the band.
 */
export function moveStrength(move: Move, value: number): number {
  const { min, max } = move.threshold;
  const tierBias = move.tier * 0.01; // tiny tie-break favoring higher tiers
  const lowIsExtreme =
    move.signal === "language_concentration" ||
    (move.signal === "commit_message_length" && move.id === "one_liner");

  if (min != null && max != null) {
    const span = max - min;
    if (span <= 0) return tierBias;
    if (lowIsExtreme || min === 0) {
      return (max - value) / span + tierBias;
    }
    return (value - min) / span + tierBias;
  }
  if (min != null) {
    // Open-ended high tier: distance past the floor, scaled by the floor.
    const scale = min > 0 ? min : 1;
    return (value - min) / scale + tierBias;
  }
  if (max != null) {
    const scale = max > 0 ? max : 1;
    return (max - value) / scale + tierBias;
  }
  return tierBias;
}

function rankMatches(signals: SignalValues): RankedMove[] {
  const matched: RankedMove[] = [];

  for (const move of MOVE_BANK) {
    const value = signals[move.threshold.metric];
    if (typeof value !== "number" || !inThreshold(value, move.threshold)) {
      continue;
    }
    matched.push({
      move,
      value,
      strength: moveStrength(move, value),
    });
  }

  // Within each signal, keep only the highest tier (guards overlapping bands).
  const bestBySignal = new Map<string, RankedMove>();
  for (const entry of matched) {
    const existing = bestBySignal.get(entry.move.signal);
    if (!existing || entry.move.tier > existing.move.tier) {
      bestBySignal.set(entry.move.signal, entry);
    }
  }

  return [...bestBySignal.values()].sort((a, b) => {
    if (b.strength !== a.strength) return b.strength - a.strength;
    if (b.move.tier !== a.move.tier) return b.move.tier - a.move.tier;
    return b.move.power - a.move.power;
  });
}

function toSelected(move: Move): SelectedMove {
  return {
    id: move.id,
    name: move.name,
    type: move.type,
    power: move.power,
    description: move.description,
    category: move.category,
    signal: move.signal,
    tier: move.tier,
  };
}

/** Bank + defaults, indexed by id for O(1) hydration after cache reads. */
const MOVE_BY_ID: Map<string, Move> = (() => {
  const map = new Map<string, Move>();
  for (const move of MOVE_BANK) map.set(move.id, move);
  for (const move of Object.values(DEFAULT_MOVES)) map.set(move.id, move);
  return map;
})();

/** Resolve a cached move id to current bank copy (name/description/etc.). */
export function resolveMove(id: string): SelectedMove {
  const move = MOVE_BY_ID.get(id);
  if (!move) {
    return toSelected(DEFAULT_MOVES.commit_style);
  }
  return toSelected(move);
}

/** Hydrate a cached `[id, id]` pair into display-ready SelectedMoves. */
export function resolveMoves(
  ids: readonly [string, string],
): [SelectedMove, SelectedMove] {
  return [resolveMove(ids[0]), resolveMove(ids[1])];
}

function pickDefault(
  usedCategories: Set<SignalCategory>,
  usedIds: Set<string>,
): Move | null {
  for (const category of CATEGORY_ORDER) {
    if (usedCategories.has(category)) continue;
    const fallback = DEFAULT_MOVES[category];
    if (!usedIds.has(fallback.id)) return fallback;
  }
  // Last resort: any unused default.
  for (const category of CATEGORY_ORDER) {
    const fallback = DEFAULT_MOVES[category];
    if (!usedIds.has(fallback.id)) return fallback;
  }
  return null;
}

/**
 * Select exactly two moves from different categories, ranked by strength.
 * Falls back to per-category defaults when GitHub data is too sparse.
 */
export function selectMoves(signals: SignalValues): [SelectedMove, SelectedMove] {
  const ranked = rankMatches(signals);
  const picked: Move[] = [];
  const usedCategories = new Set<SignalCategory>();
  const usedIds = new Set<string>();

  // Slot 1: strongest match overall.
  if (ranked[0]) {
    picked.push(ranked[0].move);
    usedCategories.add(ranked[0].move.category);
    usedIds.add(ranked[0].move.id);
  }

  // Slot 2: strongest match from a different category.
  for (const entry of ranked) {
    if (picked.length >= 2) break;
    if (usedCategories.has(entry.move.category)) continue;
    if (usedIds.has(entry.move.id)) continue;
    picked.push(entry.move);
    usedCategories.add(entry.move.category);
    usedIds.add(entry.move.id);
  }

  // If category diversity blocked a second pick, take next-highest regardless.
  if (picked.length < 2) {
    for (const entry of ranked) {
      if (picked.length >= 2) break;
      if (usedIds.has(entry.move.id)) continue;
      // Still prefer a new category when possible; only relax if necessary.
      if (usedCategories.has(entry.move.category) && picked.length === 1) {
        continue;
      }
      picked.push(entry.move);
      usedCategories.add(entry.move.category);
      usedIds.add(entry.move.id);
    }
  }

  // Absolute last resort for slot 2: ignore category constraint among matches.
  if (picked.length < 2) {
    for (const entry of ranked) {
      if (usedIds.has(entry.move.id)) continue;
      picked.push(entry.move);
      usedCategories.add(entry.move.category);
      usedIds.add(entry.move.id);
      break;
    }
  }

  // Fill remaining slots from designated defaults.
  while (picked.length < 2) {
    const fallback = pickDefault(usedCategories, usedIds);
    if (!fallback) break;
    picked.push(fallback);
    usedCategories.add(fallback.category);
    usedIds.add(fallback.id);
  }

  // Should be unreachable — defaults cover every category.
  while (picked.length < 2) {
    picked.push(DEFAULT_MOVES.commit_style);
  }

  return [toSelected(picked[0]), toSelected(picked[1])];
}

export function selectMovesForProfile(
  raw: RawGitHubData,
  signals: DerivedSignals,
): [SelectedMove, SelectedMove] {
  return selectMoves(computeSignalValues(raw, signals));
}

/** Map selected moves into the card's display shape (pips, damage, text). */
export function toCardMoves(moves: [SelectedMove, SelectedMove]): CardMove[] {
  return moves.map((move) => {
    const pipCount =
      move.power < 55 ? 1 : move.power < 85 ? 2 : 3;
    return {
      name: move.name,
      cost: Array.from({ length: pipCount }, () => move.type),
      damage: move.tier >= 3 ? `${move.power}+` : String(move.power),
      text: move.description,
    };
  });
}